# Generated by Django 3.1.7 on 2021-03-31 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bigfoot', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sighthing',
            new_name='Sighting',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='sighthing',
            new_name='sighting',
        ),
    ]
